

[module]
  [[module.imports]]
    path = "github.com/brtrdkeller/higo"
  [[module.imports]]
    path = "github.com/lowdit/fromago"
  [[module.imports]]
    path = "github.com/lowdit/repogo"
  [[module.imports]]
    path = "github.com/lowdit/sligo"
  [[module.imports]]
    path = "github.com/lowdit/frago"
