[imports]
  path = "github.com/brtrdkeller/higo"
[imports]
  path = "github.com/lowdit/fromago"
[imports]
  path = "github.com/lowdit/repogo"
[imports]
  path = "github.com/lowdit/sligo"
[imports]
  path = "github.com/lowdit/frago"
